version: "1.0"

seed: 187720

logging:
  log_dir: outputs/logs
  checkpoint_dir: outputs/checkpoints
  dashboard_dir: outputs/mlflow
  save_interval: 1

data:
  name: mnist
  params:
    data_dir: data/
    num_classes: 10
    num_workers: 4
    batch_size: 64
    dry_run_batches: 2

model:
  name: hqnn-parallel
  params:
    conv_channels: [16, 32]
    conv_kernels: [5, 5]
    conv_strides: [1, 1]
    conv_paddings: [2, 2]
    pool_sizes: [2, 2]
    num_qubits: 5
    num_qlayers: 4
    num_qrepetitions: 3
    qdevice: default.qubit
    qdiff_method: backprop

training:
  epochs: 10
  device: cpu

loss:
  name: cross-entropy
  params: none

optimizer:
  name: adam
  params:
    lr: 0.001
    weight_decay: 0.00001

scheduler:
  name: none
  params: none

search:
  method: none
  params: none